"use server"

import { unstable_noStore as noStore } from "next/cache"
import { Pagination, ApiResponse } from "@/types/api"
import { GetPatientsSchema } from "../validations/patient/search-params"
import { Patient } from "@/types/patient"

export async function getPatients(
  input: GetPatientsSchema
): Promise<ApiResponse<Pagination<Patient[]>>> {
  noStore()
  const PATIENTS: Patient[] = [
    {
      id: 1,
      fullName: "John Doe",
      dateOfBirth: new Date(1985, 4, 15),
      gender: "Male",
      address: "123 Maple Street, Springfield",
      phone: "555-1234",
      insuranceNumber: "INS12345678",
      medicalInsurance: "HealthPlus",
      lastAppointment: new Date(2024, 11, 20),
      healthStatus: "Good",
    },
    {
      id: 2,
      fullName: "Jane Smith",
      dateOfBirth: new Date(1990, 2, 28),
      gender: "Female",
      address: "456 Oak Avenue, Metropolis",
      phone: "555-5678",
      insuranceNumber: "INS87654321",
      medicalInsurance: "CareWell",
      lastAppointment: new Date(2025, 0, 10),
      healthStatus: "Excellent",
    },
    {
      id: 3,
      fullName: "Alex Johnson",
      dateOfBirth: new Date(1978, 6, 12),
      gender: "Other",
      address: "789 Pine Lane, Gotham",
      phone: "555-9012",
      insuranceNumber: "INS11223344",
      medicalInsurance: "MedSecure",
      lastAppointment: new Date(2024, 10, 5),
      healthStatus: "Fair",
    },
    {
      id: 4,
      fullName: "Emily Davis",
      dateOfBirth: new Date(2000, 3, 9),
      gender: "Female",
      address: "101 Cedar Street, Star City",
      phone: "555-3456",
      insuranceNumber: "INS33445566",
      medicalInsurance: "HealthyLife",
      lastAppointment: new Date(2024, 9, 15),
      healthStatus: "Poor",
    },
    {
      id: 5,
      fullName: "Michael Brown",
      dateOfBirth: new Date(1965, 10, 20),
      gender: "Male",
      address: "202 Birch Road, Central City",
      phone: "555-7890",
      insuranceNumber: "INS55667788",
      medicalInsurance: "CareFirst",
      lastAppointment: null,
      healthStatus: "Good",
    },
    {
      id: 6,
      fullName: "Sarah Wilson",
      dateOfBirth: new Date(1988, 7, 25),
      gender: "Female",
      address: "303 Elm Drive, Riverdale",
      phone: "555-6543",
      insuranceNumber: "INS99887766",
      medicalInsurance: "LifeSecure",
      lastAppointment: new Date(2024, 6, 12),
      healthStatus: "Excellent",
    },
    {
      id: 7,
      fullName: "Chris Taylor",
      dateOfBirth: new Date(1995, 0, 18),
      gender: "Male",
      address: "404 Willow Court, Smallville",
      phone: "555-4321",
      insuranceNumber: "INS22334455",
      medicalInsurance: "MediCare",
      lastAppointment: new Date(2023, 11, 30),
      healthStatus: "Fair",
    },
    {
      id: 8,
      fullName: "Patricia Martinez",
      dateOfBirth: new Date(1972, 8, 2),
      gender: "Female",
      address: "505 Aspen Way, Coast City",
      phone: "555-8765",
      insuranceNumber: "INS11224433",
      medicalInsurance: "PrimeHealth",
      lastAppointment: new Date(2024, 3, 20),
      healthStatus: "Poor",
    },
    {
      id: 9,
      fullName: "David Anderson",
      dateOfBirth: new Date(1998, 5, 30),
      gender: "Male",
      address: "606 Cherry Blvd, Hill Valley",
      phone: "555-9087",
      insuranceNumber: "INS33446655",
      medicalInsurance: "ShieldHealth",
      lastAppointment: null,
      healthStatus: "Good",
    },
    {
      id: 10,
      fullName: "Anna Thomas",
      dateOfBirth: new Date(1980, 1, 14),
      gender: "Female",
      address: "707 Maple Terrace, Arlen",
      phone: "555-1238",
      insuranceNumber: "INS77889900",
      medicalInsurance: "WellCare",
      lastAppointment: new Date(2024, 8, 8),
      healthStatus: "Excellent",
    },
    // {
    //   id: 11,
    //   fullName: "James White",
    //   dateOfBirth: new Date(1993, 9, 10),
    //   gender: "Male",
    //   address: "808 Spruce Alley, Springfield",
    //   phone: "555-9876",
    //   insuranceNumber: "INS12398745",
    //   medicalInsurance: "SafeHealth",
    //   lastAppointment: new Date(2024, 2, 22),
    //   healthStatus: "Fair",
    // },
    // {
    //   id: 12,
    //   fullName: "Maria Lopez",
    //   dateOfBirth: new Date(1975, 11, 5),
    //   gender: "Female",
    //   address: "909 Redwood Trail, Emerald City",
    //   phone: "555-6542",
    //   insuranceNumber: "INS66778899",
    //   medicalInsurance: "SecureLife",
    //   lastAppointment: new Date(2024, 4, 10),
    //   healthStatus: "Poor",
    // },
    // {
    //   id: 13,
    //   fullName: "Samuel Harris",
    //   dateOfBirth: new Date(1983, 2, 16),
    //   gender: "Male",
    //   address: "1010 Walnut Crescent, Metropolis",
    //   phone: "555-2109",
    //   insuranceNumber: "INS44556677",
    //   medicalInsurance: "HealthFirst",
    //   lastAppointment: null,
    //   healthStatus: "Good",
    // },
    // {
    //   id: 14,
    //   fullName: "Olivia Clark",
    //   dateOfBirth: new Date(1997, 11, 1),
    //   gender: "Female",
    //   address: "1111 Cypress Court, Gotham",
    //   phone: "555-6789",
    //   insuranceNumber: "INS55668822",
    //   medicalInsurance: "LifeCare",
    //   lastAppointment: new Date(2025, 0, 15),
    //   healthStatus: "Excellent",
    // },
    // {
    //   id: 15,
    //   fullName: "Benjamin Carter",
    //   dateOfBirth: new Date(1968, 5, 28),
    //   gender: "Male",
    //   address: "1212 Beech Avenue, Star City",
    //   phone: "555-4329",
    //   insuranceNumber: "INS00998877",
    //   medicalInsurance: "PrimeWell",
    //   lastAppointment: new Date(2024, 11, 25),
    //   healthStatus: "Fair",
    // },
  ]

  const apiResponse: ApiResponse<Pagination<Patient[]>> = {
    error: false,
    statusCode: 200,
    message: "",
    payload: {
      limit: 10,
      page: 1,
      pageCount: 2,
      total: 15,
      data: PATIENTS,
    },
  }

  return apiResponse
}

export async function getPatient({ id }: { id: number }) {
  const PATIENTS: Patient[] = [
    {
      id: 1,
      fullName: "John Doe",
      dateOfBirth: new Date(1985, 4, 15),
      gender: "Male",
      address: "123 Maple Street, Springfield",
      phone: "555-1234",
      insuranceNumber: "INS12345678",
      medicalInsurance: "HealthPlus",
      lastAppointment: new Date(2024, 11, 20),
      healthStatus: "Good",
    },
    {
      id: 2,
      fullName: "Jane Smith",
      dateOfBirth: new Date(1990, 2, 28),
      gender: "Female",
      address: "456 Oak Avenue, Metropolis",
      phone: "555-5678",
      insuranceNumber: "INS87654321",
      medicalInsurance: "CareWell",
      lastAppointment: new Date(2025, 0, 10),
      healthStatus: "Excellent",
    },
    {
      id: 3,
      fullName: "Alex Johnson",
      dateOfBirth: new Date(1978, 6, 12),
      gender: "Other",
      address: "789 Pine Lane, Gotham",
      phone: "555-9012",
      insuranceNumber: "INS11223344",
      medicalInsurance: "MedSecure",
      lastAppointment: new Date(2024, 10, 5),
      healthStatus: "Fair",
    },
    {
      id: 4,
      fullName: "Emily Davis",
      dateOfBirth: new Date(2000, 3, 9),
      gender: "Female",
      address: "101 Cedar Street, Star City",
      phone: "555-3456",
      insuranceNumber: "INS33445566",
      medicalInsurance: "HealthyLife",
      lastAppointment: new Date(2024, 9, 15),
      healthStatus: "Poor",
    },
    {
      id: 5,
      fullName: "Michael Brown",
      dateOfBirth: new Date(1965, 10, 20),
      gender: "Male",
      address: "202 Birch Road, Central City",
      phone: "555-7890",
      insuranceNumber: "INS55667788",
      medicalInsurance: "CareFirst",
      lastAppointment: null,
      healthStatus: "Good",
    },
    {
      id: 6,
      fullName: "Sarah Wilson",
      dateOfBirth: new Date(1988, 7, 25),
      gender: "Female",
      address: "303 Elm Drive, Riverdale",
      phone: "555-6543",
      insuranceNumber: "INS99887766",
      medicalInsurance: "LifeSecure",
      lastAppointment: new Date(2024, 6, 12),
      healthStatus: "Excellent",
    },
    {
      id: 7,
      fullName: "Chris Taylor",
      dateOfBirth: new Date(1995, 0, 18),
      gender: "Male",
      address: "404 Willow Court, Smallville",
      phone: "555-4321",
      insuranceNumber: "INS22334455",
      medicalInsurance: "MediCare",
      lastAppointment: new Date(2023, 11, 30),
      healthStatus: "Fair",
    },
    {
      id: 8,
      fullName: "Patricia Martinez",
      dateOfBirth: new Date(1972, 8, 2),
      gender: "Female",
      address: "505 Aspen Way, Coast City",
      phone: "555-8765",
      insuranceNumber: "INS11224433",
      medicalInsurance: "PrimeHealth",
      lastAppointment: new Date(2024, 3, 20),
      healthStatus: "Poor",
    },
    {
      id: 9,
      fullName: "David Anderson",
      dateOfBirth: new Date(1998, 5, 30),
      gender: "Male",
      address: "606 Cherry Blvd, Hill Valley",
      phone: "555-9087",
      insuranceNumber: "INS33446655",
      medicalInsurance: "ShieldHealth",
      lastAppointment: null,
      healthStatus: "Good",
    },
    {
      id: 10,
      fullName: "Anna Thomas",
      dateOfBirth: new Date(1980, 1, 14),
      gender: "Female",
      address: "707 Maple Terrace, Arlen",
      phone: "555-1238",
      insuranceNumber: "INS77889900",
      medicalInsurance: "WellCare",
      lastAppointment: new Date(2024, 8, 8),
      healthStatus: "Excellent",
    },
    // {
    //   id: 11,
    //   fullName: "James White",
    //   dateOfBirth: new Date(1993, 9, 10),
    //   gender: "Male",
    //   address: "808 Spruce Alley, Springfield",
    //   phone: "555-9876",
    //   insuranceNumber: "INS12398745",
    //   medicalInsurance: "SafeHealth",
    //   lastAppointment: new Date(2024, 2, 22),
    //   healthStatus: "Fair",
    // },
    // {
    //   id: 12,
    //   fullName: "Maria Lopez",
    //   dateOfBirth: new Date(1975, 11, 5),
    //   gender: "Female",
    //   address: "909 Redwood Trail, Emerald City",
    //   phone: "555-6542",
    //   insuranceNumber: "INS66778899",
    //   medicalInsurance: "SecureLife",
    //   lastAppointment: new Date(2024, 4, 10),
    //   healthStatus: "Poor",
    // },
    // {
    //   id: 13,
    //   fullName: "Samuel Harris",
    //   dateOfBirth: new Date(1983, 2, 16),
    //   gender: "Male",
    //   address: "1010 Walnut Crescent, Metropolis",
    //   phone: "555-2109",
    //   insuranceNumber: "INS44556677",
    //   medicalInsurance: "HealthFirst",
    //   lastAppointment: null,
    //   healthStatus: "Good",
    // },
    // {
    //   id: 14,
    //   fullName: "Olivia Clark",
    //   dateOfBirth: new Date(1997, 11, 1),
    //   gender: "Female",
    //   address: "1111 Cypress Court, Gotham",
    //   phone: "555-6789",
    //   insuranceNumber: "INS55668822",
    //   medicalInsurance: "LifeCare",
    //   lastAppointment: new Date(2025, 0, 15),
    //   healthStatus: "Excellent",
    // },
    // {
    //   id: 15,
    //   fullName: "Benjamin Carter",
    //   dateOfBirth: new Date(1968, 5, 28),
    //   gender: "Male",
    //   address: "1212 Beech Avenue, Star City",
    //   phone: "555-4329",
    //   insuranceNumber: "INS00998877",
    //   medicalInsurance: "PrimeWell",
    //   lastAppointment: new Date(2024, 11, 25),
    //   healthStatus: "Fair",
    // },
  ]
  const PATIENT = PATIENTS.find((patient) => patient.id === id)
  return PATIENT
}
